apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: adeschamps
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/adeschamps-harbor-project/db@sha256:6a73ccc4bcb1b317b2e7168695baeb6bd641e7e3e3d2d63d14a6865a7e5b14ef
        ports:
        - containerPort: 5432
